// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLSugQiq46tF-bBfNa4YcDVZksvUxxXok',
    appId: '1:951679074629:web:d0a31a6ef20bae38543e2c',
    messagingSenderId: '951679074629',
    projectId: 'bitirme-34bb3',
    authDomain: 'bitirme-34bb3.firebaseapp.com',
    storageBucket: 'bitirme-34bb3.appspot.com',
    measurementId: 'G-CMXT1M4CV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_LuRiCmjk9KwHQwN26Z6JSuys9rVeWlk',
    appId: '1:951679074629:android:9cd371b09f27b866543e2c',
    messagingSenderId: '951679074629',
    projectId: 'bitirme-34bb3',
    storageBucket: 'bitirme-34bb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzNEGfBk4we_xDX1vVACMwQphOZ5palwo',
    appId: '1:951679074629:ios:bc42ff4e89842a9e543e2c',
    messagingSenderId: '951679074629',
    projectId: 'bitirme-34bb3',
    storageBucket: 'bitirme-34bb3.appspot.com',
    iosClientId: '951679074629-g9bgoj5gjae90edok0dfa3hmgfssktnn.apps.googleusercontent.com',
    iosBundleId: 'fu.fuat.bookreviewer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzNEGfBk4we_xDX1vVACMwQphOZ5palwo',
    appId: '1:951679074629:ios:823e1d9f9d7ebe12543e2c',
    messagingSenderId: '951679074629',
    projectId: 'bitirme-34bb3',
    storageBucket: 'bitirme-34bb3.appspot.com',
    iosClientId: '951679074629-6hvuhuv2vqsrnofvah0lllvbq3iqj132.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookReviewer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbTt0iah5pejElElDxE6Z6w_kkgQ8e5Os',
    appId: '1:951679074629:web:a369412512de960e543e2c',
    messagingSenderId: '951679074629',
    projectId: 'bitirme-34bb3',
    authDomain: 'bitirme-34bb3.firebaseapp.com',
    storageBucket: 'bitirme-34bb3.appspot.com',
    measurementId: 'G-CY0QT2RWGF',
  );
}
